# Generated by Django 5.2.12 on 2026-10-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_stationdispatch_dispatch_liters2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelinventory',
            name='tank1_cm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fuelinventory',
            name='tank1_liters',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fuelinventory',
            name='tank2_cm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fuelinventory',
            name='tank2_liters',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fuelinventory',
            name='tank3_cm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fuelinventory',
            name='tank3_liters',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
