# Generated by Django 5.2.12 on 2026-10-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_alter_fuelinventory_tank1_cm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelinventory',
            name='tank1_cm',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='fuelinventory',
            name='tank2_cm',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='fuelinventory',
            name='tank3_cm',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True),
        ),
    ]
